name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet run
    - name: Git Push Action
      uses: x-actions/git-push@v1
      with:
        GITHUB_EMAIL: jj.bussert@gmail.com
        GITHUB_USERNAME: e13tech
        PUBLISH_REPO: https://${{ secrets.BLOG_PUSH_ACTION }}@github.com/e13tech/blog-static.git
        PUBLISH_BRANCH: stage
        PUBLISH_DIR: ./output
